//
//  NSError+Errno.h
//  WordBase
//
//  Created by Dmitry Feld on 8/4/16.
//  Copyright © 2016 Dmitry Feld. All rights reserved.
//

#import <Foundation/Foundation.h>

extern const NSString* kDFWBErrnoErrorsDomain;

typedef enum __DFWBErrnoCodes__:NSUInteger {
    kDFWBOperationNotPermitted = 1,
    kDFWBNoSuchFileOrDirectory,
    kDFWBNoSuchProcess,
    kDFWBInterruptedSystemCall,
    kDFWBIOError,
    kDFWBNoSuchDeviceOrAddress,
    kDFWBArgumentListTooLong,
    kDFWBExecFormatError,
    kDFWBBadFileNumber,
    kDFWBNoChildProcessed,
    kDFWBTryAgain,
    kDFWBOutOfMemory,
    kDFWBPermissionDenied,
    kDFWBBadAddress,
    kDFWBBlcokDeviceRequired,
    kDFWBDeviceOrResourceBusy,
    kDFWBFileExists,
    kDFWBCrossDeviceLink,
    kDFWBNoSuchDevice,
    kDFWBNotADirectory,
    kDFWBIsADirectory,
    kDFWBInvalidArgument,
    kDFWBFileTableOverflow,
    kDFWBTooManyOpenFiles,
    kDFWBNotATypewriter,
    kDFWBTextFileTooBusy,
    kDFWBFileTooLarge,
    kDFWBNoSpaceLeftOnDevice,
    kDFWBIllegalSeek,
    kDFWBReadOnlyFileSystem,
    kDFWBTooManyLinks,
    kDFWBBrokenPipe,
    kDFWBMathArgOutOfDomainOfFunc,
    kDFWBMathResultNotRepresentable,
    
    kDFWBResourceDeadlockWouldOccur,
    kDFWBFileNameTooLong,
    kDFWBNoRecordLocksAvailable,
    kDFWBFunctionNotImplemented,
    kDFWBDirectoryNotEmpty,
    kDFWBTooManySymbolicLinks,
    kDFWBOperationWouldBlock,
    kDFWBNoMessageOfDesiredType,
    kDFWBIdentifierRemoved,
    kDFWBChannelNumberOutOfRange,
    kDFWBLevel2NotSynchronized,
    kDFWBLevel3Halted,
    kDFWBLevel3Reset,
    kDFWBLinkNumberOutOfRange,
    kDFWBProtocolDriverNotAttached,
    kDFWBNoCSIStructureAvailable,
    kDFWBLevel2Halted,
    kDFWBInvalidExchange,
    kDFWBInvalidRequestDescriptor,
    kDFWBExchangeFull,
    kDFWBNoAnode,
    kDFWBInvalidRequestCode,
    kDFWBInvalidSlot,
    
    kDFWBDeadlock,
    
    kDFWBBadFontFileFormat,
    kDFWBDeviceNotAStream,
    kDFWBNoDataAvailable,
    kDFWBTimerExpired,
    kDFWBOutOfStreamsResources,
    kDFWBMachineIsNotOnTheNetwork,
    kDFWBPackageNotInstalled,
    kDFWBObjectIsRemote,
    kDFWBLinkHasBeenSevered,
    kDFWBAdvertiseError,
    kDFWBSrmountError,
    kDFWBCommunicationErrorOnSend,
    kDFWBProtocolError,
    kDFWBMultihopAttempted,
    kDFWBRFSSpecificError,
    kDFWBNotADataMessage,
    kDFWBValueTooLarge,
    kDFWBNameNotUniqueOnNetwork,
    kDFWBFileDescriptorInBadState,
    kDFWBRemoteAddressChanged,
    kDFWBCanNotAccessLibrary,
    kDFWBAccessingCorruptedLibrary,
    kDFWBLibSectionInAOutCorrupted,
    kDFWBTooManyAttemptsToLink,
    kDFWBCannotExecSharedLibrary,
    kDFWBIllegalByteSequence,
    kDFWBSystemCallShouldRestart,
    kDFWBStreamsPipeError,
    kDFWBTooManyUsers,
    kDFWBInvalicSocketOperation,
    kDFWBDestinationAddressRequired,
    kDFWBMessageTooLong,
    kDFWBInvalidProtocolType,
    kDFWBProtocolNotAvailable,
    kDFWBProtocolNotSupported,
    kDFWBSocketTypeNotSupported,
    kDFWBOperationNotSupported,
    kDFWBProtocolFamilyNotSupported,
    kDFWBAddressFamilyNotSupported,
    kDFWBAddressAlreadyInUse,
    kDFWBCannotAssignAddress,
    kDFWBNetworkIsDown,
    kDFWBNetworkIsUnreachable,
    kDFWBNetworkReset,
    kDFWBSoftwareConnectionAbort,
    kDFWBConnectionResetByPeer,
    kDFWBNoBufferSpaceAvailable,
    kDFWBTransportIsConnected,
    kDFWBTransportNotConnected,
    kDFWBCannotSend,
    kDFWBTooManyReferences,
    kDFWBConnectionTimedOut,
    kDFWBConnectionRefused,
    kDFWBHostIsDown,
    kDFWBNoRouteToHost,
    kDFWBOperationAlreadyInProgress,
    kDFWBOperationNowInProgress,
    kDFWBStaleNFSFileHandle,
    kDFWBStructureNeedsCleaning,
    kDFWBNotXENIXNamedTypeFile,
    kDFWBNoXENIXSemaphores,
    kDFWBIsNamedTypeFile,
    kDFWBRemoteIOError,
    kDFWBQuotaExceeded,
    
    kDFWBNoMediumFound,
    kDFWBWrongMediumType,
    kDFWBOperationCanceled,
    kDFWBKeyNotAvailable,
    kDFWBKeyExpired,
    kDFWBKeyRevoked,
    kDFWBKeyWasRejected,
    
    kDFWBOwnerDied,
    kDFWBStateNotRecoverable,
    
    kDFWBFileAlreadyOpen,
    kDFWBFileAlreadyClosed
} DFWBErrnoCodes;


@interface NSError(Errno)
+ (NSError*) errorWithCode:(uint16_t)code;
@end
